name: Build Alpine for RG353VS SD‑Card

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable QEMU emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build Docker image + run builder
        run: |
          docker build -t alpine-rg353vs-builder .
          mkdir -p out
          docker run --rm \
            -v "${{ github.workspace }}:/work" \
            alpine-rg353vs-builder

      - name: Upload SD‑card image
        uses: actions/upload-artifact@v3
        with:
          name: rg353vs-alpine-sdcard
          path: out/rg353vs-alpine.img
