name: Build & Release Alpine RG353VS SD-Card Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push multi-arch image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:latest
            ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}

      - name: Save container tarball
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}
          docker pull "$IMAGE"
          docker save "$IMAGE" | gzip > alpine-rg353vs-${{ github.sha }}.tar.gz

      - name: Upload container artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-${{ github.sha }}
          path: alpine-rg353vs-${{ github.sha }}.tar.gz

  make-sd-image:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Install host deps
        run: |
          sudo apt-get update
          sudo apt-get install -y wget parted dosfstools e2fsprogs kmod u-boot-tools

      - name: Download rootfs & prepare boot files
        run: |
          wget -O rootfs.tar.gz http://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/aarch64/alpine-minirootfs-3.22.0-aarch64.tar.gz
          # stage your files into CWD:
          cp linux         zImage
          cp dtb/rk3566-rg353v.dtb rk3566.dtb
          cp extlinux/extlinux.conf extlinux.conf

      - name: Build SD‑card image
        run: |
          set -euxo pipefail
          SHA=${{ github.sha }}
          IMG=alpine-rg353vs-${SHA}.img

          # 1) create blank 1 GiB file
          truncate -s 1G "$IMG"

          # 2) partition it directly
          LOOP=$(sudo losetup --show -fP "$IMG")
          sudo parted --script "$LOOP" \
            mklabel msdos \
            mkpart primary fat32 1MiB 64MiB \
            mkpart primary ext4  64MiB 100%

          # 3) format partitions
          sudo mkfs.vfat -n BOOT "${LOOP}p1"
          sudo mkfs.ext4 -L ROOTFS "${LOOP}p2"

          # 4) flash U‑Boot at 8 KiB
          sudo dd if=uboot.img of="$LOOP" bs=1K seek=8 conv=fsync

          # 5) mount & populate
          mkdir -p mnt/boot mnt/root
          sudo mount "${LOOP}p1" mnt/boot
          sudo mount "${LOOP}p2" mnt/root

          sudo tar xzf rootfs.tar.gz -C mnt/root
          sudo cp zImage            mnt/boot/
          sudo cp rk3566.dtb        mnt/boot/
          sudo mkdir -p mnt/boot/extlinux
          sudo cp extlinux.conf     mnt/boot/extlinux/extlinux.conf

          # 6) cleanup
          sync
          sudo umount mnt/boot mnt/root
          sudo losetup -d "$LOOP"

      - name: Upload SD‑Card artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdcard-${{ github.sha }}
          path: alpine-rg353vs-${{ github.sha }}.img


  package-release:
    name: Create GitHub Release & Attach Assets
    needs: [build-and-push, make-sd-image]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            - **Container**: ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}
            - **SD-Card image**: alpine-rg353vs-${{ github.ref_name }}.img
            - **Container tarball**: alpine-rg353vs-${{ github.ref_name }}.tar.gz
          draft: false
          prerelease: false

      - name: Upload SD-Card release asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/alpine-rg353vs-${{ github.sha }}.img
          asset_name: alpine-rg353vs-${{ github.ref_name }}.img
          asset_content_type: application/octet-stream

      - name: Upload container release asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/alpine-rg353vs-${{ github.sha }}.tar.gz
          asset_name: alpine-rg353vs-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
