name: Build & Release Alpine RG353VS SD-Card Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:latest
            ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}

      - name: Save container tarball
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}
          docker pull "$IMAGE"
          docker save "$IMAGE" | gzip > alpine-rg353vs-${{ github.sha }}.tar.gz

      - name: Upload container artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-${{ github.sha }}
          path: alpine-rg353vs-${{ github.sha }}.tar.gz

  make-sd-image:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget parted dosfstools e2fsprogs kmod u-boot-tools

      - name: Build SD-Card Image
        run: |
          set -euxo pipefail
          SHA=${{ github.sha }}
          IMG=alpine-rg353vs-${SHA}.img
          UBOOT=uboot.img
          MINIROOT=http://dl-cdn.alpinelinux.org/alpine/v3.19/releases/aarch64/alpine-minirootfs-3.19.0-aarch64.tar.gz

          # download rootfs
          wget -O rootfs.tar.gz "$MINIROOT"

          # create blank image
          truncate -s 1G "$IMG"

          # attach loop device and force partition scanning
          LOOP=$(sudo losetup --show -fP "$IMG")

          # partition the loop device
          sudo parted --script "$LOOP" \
            mklabel msdos \
            mkpart primary fat32 1MiB 64MiB \
            mkpart primary ext4  64MiB 100%

          # notify kernel of partition table changes
          sudo partprobe "$LOOP"

          # define partition devices
          BOOT_DEV="${LOOP}p1"
          ROOT_DEV="${LOOP}p2"

          # format partitions
          sudo mkfs.vfat -n BOOT "$BOOT_DEV"
          sudo mkfs.ext4 -L ROOTFS "$ROOT_DEV"

          # install u-boot at 8KiB offset
          sudo dd if="$UBOOT" of="$LOOP" bs=1K seek=8 conv=fsync

          # mount and populate
          mkdir -p mnt/boot mnt/root
          sudo mount "$BOOT_DEV" mnt/boot
          sudo mount "$ROOT_DEV" mnt/root

          sudo tar xzf rootfs.tar.gz -C mnt/root
          sudo cp zImage mnt/boot/
          sudo cp *.dtb mnt/boot/
          sudo cp boot.scr mnt/boot/

          # cleanup
          sync
          sudo umount mnt/boot mnt/root
          sudo losetup -d "$LOOP"

          ls -lh "$IMG"

      - name: Upload SD-Card artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdcard-${{ github.sha }}
          path: alpine-rg353vs-${{ github.sha }}.img

  package-release:
    needs: [build-and-push, make-sd-image]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            - Container: ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}
            - SD-Card image: alpine-rg353vs-${{ github.ref_name }}.img
            - Container tarball: alpine-rg353vs-${{ github.ref_name }}.tar.gz

      - name: Upload SD-Card asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: artifacts/alpine-rg353vs-${{ github.sha }}.img
          asset_name: alpine-rg353vs-${{ github.ref_name }}.img
          asset_content_type: application/octet-stream

      - name: Upload container asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: artifacts/alpine-rg353vs-${{ github.sha }}.tar.gz
          asset_name: alpine-rg353vs-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
