name: Build & Release Alpine RG353VS SD‑Card Image (guestfish)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  # 1️⃣ Build & push the container image
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push multi‑arch image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:latest
            ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}

      - name: Save container tarball
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}
          docker pull "$IMAGE"
          docker save "$IMAGE" | gzip > alpine-rg353vs-${{ github.sha }}.tar.gz

      - name: Upload container artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-${{ github.sha }}
          path: alpine-rg353vs-${{ github.sha }}.tar.gz

  # 2️⃣ Build the SD‑Card image using guestfish
  make-sd-image:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget libguestfs-tools

           - name: Build SD‑Card Image with guestfish
             run: |
               set -euxo pipefail
               SHA=${{ github.sha }}
               IMG=alpine-rg353vs-${SHA}.img
               UBOOT=uboot.img
               ROOTFS_TAR=http://dl-cdn.alpinelinux.org/alpine/v3.19/releases/aarch64/alpine-minirootfs-3.19.0-aarch64.tar.gz
      
               wget -O rootfs.tar.gz "$ROOTFS_TAR"
               truncate -s 1G "$IMG"
      
               # Correct guestfish invocation: open image as raw disk, then run commands
               sudo guestfish --format=raw -a "$IMG" <<EOF
run
part-init /dev/sda mbr
part-add   /dev/sda primary fat32 1MiB 64MiB
part-add   /dev/sda primary ext4 64MiB 100%
part-set-bootable /dev/sda 1 true
mkfs vfat /dev/sda1
mkfs ext4 /dev/sda2
dd if=$UBOOT of=/dev/sda bs=512 seek=16
mount /dev/sda2 /
mkdir /boot
mount /dev/sda1 /boot
tar-in rootfs.tar.gz /
copy-in zImage    /boot/
copy-in *.dtb     /boot/
copy-in boot.scr  /boot/
sync
umount-all
EOF

              ls -lh "$IMG"


      - name: Upload SD‑Card artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdcard-${{ github.sha }}
          path: alpine-rg353vs-${{ github.sha }}.img

  # 3️⃣ On tag pushes, make a GitHub Release
  package-release:
    needs: [build-and-push, make-sd-image]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            - **Container**: ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}
            - **SD‑Card image**: alpine-rg353vs-${{ github.ref_name }}.img
            - **Container tarball**: alpine-rg353vs-${{ github.ref_name }}.tar.gz
          draft: false
          prerelease: false

      - name: Upload SD‑Card release asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: artifacts/alpine-rg353vs-${{ github.sha }}.img
          asset_name: alpine-rg353vs-${{ github.ref_name }}.img
          asset_content_type: application/octet-stream

      - name: Upload container release asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: artifacts/alpine-rg353vs-${{ github.sha }}.tar.gz
          asset_name: alpine-rg353vs-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
