name: Build & Release Alpine RG353VS SD-Card Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push multi-arch image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:latest
            ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}

      - name: Save container tarball
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}
          docker pull "$IMAGE"
          docker save "$IMAGE" | gzip > alpine-rg353vs-${{ github.sha }}.tar.gz

      - name: Upload container artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-${{ github.sha }}
          path: alpine-rg353vs-${{ github.sha }}.tar.gz

  make-sd-image:
    name: Build SD-Card Image
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget libguestfs-tools

      - name: Download and decompress Alpine rootfs
        run: |
          wget -O rootfs.tar.gz \
            http://dl-cdn.alpinelinux.org/alpine/v3.19/releases/aarch64/alpine-minirootfs-3.19.0-aarch64.tar.gz
          gunzip -c rootfs.tar.gz > rootfs.tar
          
      - name: Create & populate image with guestfish
        run: |
          set -euxo pipefail
          SHA=${{ github.sha }}
          IMG=alpine-rg353vs-${SHA}.img

          # create blank 1 GiB image
          truncate -s 1G "$IMG"

          # partition, format, and inject via guestfish
          sudo guestfish --format=raw -a "$IMG" <<-'EOF'
            run
            part-init /dev/sda mbr
            part-add  /dev/sda p 2048 131071
            part-add  /dev/sda p 131072 -1
            part-set-bootable /dev/sda 1 true
            mkfs vfat /dev/sda1
            mkfs ext4 /dev/sda2
            mount /dev/sda2 /
            mkdir /boot
            mount /dev/sda1 /boot
            mkdir /boot/dtb
            mkdir /boot/extlinux
            tar-in rootfs.tar /
            upload /github/workspace/boot/linux /boot/linux
            upload /github/workspace/dtb/rk3566-rg353v.dtb /boot/dtb/rk3566.dtb
            upload /github/workspace/extlinux/extlinux.conf  /boot/extlinux/extlinux.conf
            sync
            umount-all
            exit
          EOF

      - name: Flash U-Boot via dd
        run: |
          dd if=uboot.img of=alpine-rg353vs-${{ github.sha }}.img bs=1K seek=8 conv=fsync

      - name: Upload SD-Card artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdcard-${{ github.sha }}
          path: alpine-rg353vs-${{ github.sha }}.img

  package-release:
    name: Create GitHub Release & Attach Assets
    needs: [build-and-push, make-sd-image]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            - **Container**: ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}
            - **SD-Card image**: alpine-rg353vs-${{ github.ref_name }}.img
            - **Container tarball**: alpine-rg353vs-${{ github.ref_name }}.tar.gz
          draft: false
          prerelease: false

      - name: Upload SD-Card release asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/alpine-rg353vs-${{ github.sha }}.img
          asset_name: alpine-rg353vs-${{ github.ref_name }}.img
          asset_content_type: application/octet-stream

      - name: Upload container release asset
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/alpine-rg353vs-${{ github.sha }}.tar.gz
          asset_name: alpine-rg353vs-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
