# .github/workflows/docker-image.yml
name: Build and Publish Alpine RG353VS Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:latest
          ghcr.io/${{ github.repository_owner }}/alpine-rg353vs:${{ github.sha }}

    - name: Image digest
      run: echo "Published image digest: ${{ steps.build-and-push.outputs.digest }}"
