name: Generate Alpine ARM64 initrd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-initrd:
    runs-on: ubuntu-latest

    steps:
      - name: Download Alpine minirootfs
        run: |
          URL="http://dl-cdn.alpinelinux.org/alpine/v3.22/releases/aarch64/alpine-minirootfs-3.22.0-aarch64.tar.gz"
          wget -O alpine-minirootfs.tar.gz "$URL"

      - name: Install host deps for ARM chroot
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support

      - name: Unpack rootfs and prepare chroot
        run: |
          mkdir rootfs
          tar xzf alpine-minirootfs.tar.gz -C rootfs
          # Enable DNS inside chroot:
          sudo cp /etc/resolv.conf rootfs/etc/
          # Register ARM emulation
          sudo cp /usr/bin/qemu-aarch64-static rootfs/usr/bin/
          # Mount necessary pseudo-filesystems
          for fs in dev proc sys; do sudo mount --bind /$fs rootfs/$fs; done

      - name: Install mkinitfs & kernel inside chroot
        run: |
          sudo chroot rootfs /bin/sh -euxc "
            # now networking works
            apk update
            apk add mkinitfs linux-virt
          "

      - name: Generate initrd
        run: |
          sudo chroot rootfs /bin/sh -euxc "
            mkinitfs -c /etc/mkinitfs/mkinitfs.conf -o /initrd-arm64.gz
          "

      - name: Cleanup chroot mounts
        run: |
          for fs in dev proc sys; do sudo umount rootfs/$fs; done

      - name: Upload initrd.gz
        uses: actions/upload-artifact@v4
        with:
          name: alpine-initrd-arm64
          path: initrd-arm64.gz
